# Generated by Django 5.1 on 2024-10-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskReminder',
        ),
    ]
